feature/awards-deeds(second page)
aberikashvili/cc-angular pull request #15
Opened 2023-05-13 01:29 UTC by NikaBeruashvilii

2023-05-17 23:08 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.scss
BEM:

```
.awards {
  margin-top: 200px;

  &__title {
    width: 436px;
    height: 54px;
    font-family: 'AvenirNextGeorgian-Bold';
    font-style: normal;
    font-weight: 700;
    font-size: 36px;
    line-height: 150%;
    display: flex;
    align-items: center;
    color: #141414;
  }

  &__img-container {
    box-sizing: border-box;
    width: 250px;
    height: 250px;
    border: 1px solid rgba(20, 20, 20, 0.1);
    display: flex;
    justify-content: center;
    align-items: center;
  }
}
```

2023-05-17 23:08 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:09 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:09 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:09 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:09 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:09 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:09 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:09 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:10 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:10 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:10 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:10 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:10 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:10 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:10 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:10 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:11 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +        <div class="img-container">
```suggestion
        <div class="awards __img-container">
```

2023-05-17 23:11 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +      <div class="flex gap-5 flex-row ...">
`...` მოაცილე

2023-05-17 23:11 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +    <div class="flex flex-col ...">
`...` მოაცილე

2023-05-17 23:12 UTC, aberikashvili commented on src/app/modules/home/components/awards-deeds-section-second/awards-deeds-section-second.component.html
> +  <div class="title--section">
```suggestion
  <div class="awards__title">
```

2023-05-17 23:14 UTC, aberikashvili commented on src/app/modules/home/home.component.html
> +  <app-awards-deeds-section-second></app-awards-deeds-section-second>
`app-awards-deeds-section` და `app-awards-deeds-section-second` ორივე რატომ გვაქვს?
თუ ერთერთს არ ვიყენებთ წაშალე

2023-05-17 23:15 UTC, aberikashvili commented on src/app/modules/home/home.component.html
> +  <!-- <app-footer></app-footer> -->
დაკომენტარებულ კოდს არ ვტოვებთ:
1. რაც საჭირო არაა - ვშლით
2. რაც საჭიროა - ვხსნით კომენტარს

2023-05-17 23:15 UTC, aberikashvili requested changes
მცირე რეფაქტორინგია საჭირო

2023-05-18 08:52 UTC, NikaBeruashvilii commented
მზადაა დასამერჯად

2023-05-18 09:36 UTC, aberikashvili approved these changes

2023-05-18 09:36 UTC, merged