Feature/tkveni-saimedo-partniorebi
aberikashvili/cc-angular pull request #17
Opened 2023-05-18 12:23 UTC by NikaBeruashvilii

2023-05-22 21:44 UTC, aberikashvili commented on src/app/modules/about-us-page/about-us-page.component.scss
> +.layout {
ეს კლასი გლობალურია, `styles.scss` -შია აღწერილი, ჯობია იქ დაამატო ეს `max-width`-ი და აქედან და home-დან წაშალო

2023-05-22 21:50 UTC, aberikashvili commented on src/app/modules/about-us-page/components/your-reliable-partners-section/your-reliable-partners-section.component.scss
ბლოკებს თუ empty line -ით გამოყოფ, უკეთ წასაკითხი იქნება

![image](https://github.com/aberikashvili/cc-angular/assets/3863691/5ed3be36-df0b-49aa-8149-bb5dc16d21c2)

2023-05-22 21:51 UTC, aberikashvili commented on src/app/modules/about-us-page/components/our-team-section/our-team-section.component.scss
> -// .heading__arrow {
კარგია რომ დაკომენტარებული კოდი წაშალე 👍

2023-05-22 21:52 UTC, aberikashvili requested changes
ორი კომენატარია შესასწორებელი

2023-05-22 22:39 UTC, NikaBeruashvilii commented on src/app/modules/about-us-page/components/your-reliable-partners-section/your-reliable-partners-section.component.scss
მზადაა

2023-05-22 22:39 UTC, NikaBeruashvilii commented on src/app/modules/about-us-page/components/our-team-section/our-team-section.component.scss
> -// .heading__arrow {
მადლობა <3

2023-05-22 22:40 UTC, NikaBeruashvilii commented
მზადაა არკად დასამერჯად

2023-05-23 09:17 UTC, aberikashvili approved these changes

2023-05-23 09:18 UTC, merged