feature/sxva-proektebi
aberikashvili/cc-angular pull request #21
Opened 2023-05-29 10:26 UTC by NikaBeruashvilii

2023-06-01 21:54 UTC, aberikashvili commented on src/app/app-routing.module.ts
> +    path: 'other-projects',
როუტის სახელი ძალიან არაინტუიტიურია. `project` დაარქვი როუტს და ასევე უნდა ჰქონდეს პარამეტერი `:id`

2023-06-01 21:54 UTC, aberikashvili commented on src/app/modules/project-details/components/other-projects/other-projects.component.scss
> +.slider {
**Rule:** readability first
```suggestion
}

.slider {
```

2023-06-01 21:55 UTC, aberikashvili commented on src/app/modules/project-details/components/other-projects/other-projects.component.scss
> +.cont__div {
**Rule:** readability first
```suggestion
}

.cont__div {
```

2023-06-01 21:55 UTC, aberikashvili commented on src/app/modules/project-details/components/other-projects/other-projects.component.scss
> +.title {
**Rule:** readability first
```suggestion
}

.title {
```

2023-06-01 22:01 UTC, aberikashvili commented on src/app/modules/projects-page/components/our-projects/our-projects.component.ts
> +  List: any[] = [
პატარა ასოთი იწყებოდეს

2023-06-01 22:02 UTC, aberikashvili commented on src/app/modules/projects-page/components/our-projects/our-projects.component.ts
> +  filterMode = 'all';
**Rule:** readability first

კლასის თვისებებს ვწერთ კონსტრუქტორის ზემოთ
```suggestion
  selectedFilter: FilterMode = FilterMode.All;
  filterMode = 'all';
  
  constructor(public router: Router) {}
```

2023-06-01 22:03 UTC, aberikashvili commented on src/app/modules/projects-page/components/our-projects/our-projects.component.ts
> +  constructor(public router: Router) {}
`public` მოდიფიკატორი მგონი არ გჭირდება აქ, `private _router: Router`

2023-06-01 22:10 UTC, aberikashvili commented on src/app/modules/projects-page/components/our-projects/enums.ts
ეს ნაწილი მახსოვს რომ დავმერჯეთ უკვე და აქ რატომ არის ისევ?

Rebase გააკეთე

2023-06-01 22:10 UTC, aberikashvili requested changes
Rebase გააკეთე პირველ რიგში და რამდენიმე კომენტარი რაც დავწერე შეასწორე

2023-06-02 10:25 UTC, NikaBeruashvilii commented
Rebase gavakete magram konfliktebi araa :დ axla mivxedavmag sakmeebs

2023-06-02 10:34 UTC, NikaBeruashvilii commented on src/app/modules/projects-page/components/our-projects/enums.ts
imitoro mag page dan unda. moxdes ak gadmosvla da buttons logika mivabi ubralod

2023-06-02 10:35 UTC, NikaBeruashvilii commented
ყველაფერი მზადააა იმ გამეორებული ლოგიკის გარდა და ამშემთხვევაში ასე რომ იყოს და შემდეგისთვის გავითვალისწინოთ?

2023-06-02 12:52 UTC, merged