feature/slider-shared-component
aberikashvili/cc-angular pull request #24
Opened 2023-06-05 08:37 UTC by NikaBeruashvilii

2023-06-08 13:47 UTC, aberikashvili commented on src/app/modules/axalcixe-smart/axalcixe-smart.component.html
ეს კოდი უკვე არის `main`-ში, rebase გაქვს გასაკეთებელი

2023-06-08 13:53 UTC, aberikashvili commented on src/app/shared/components/slider/slider.component.scss
readability

2023-06-08 13:54 UTC, aberikashvili commented on src/app/shared/components/slider/slider.component.ts
> +  @Input() heading?: string;
ეს `optional` რატომ არის? დიზაინში ხომ ყველგან აქვს ჰედინგი?

2023-06-08 13:55 UTC, aberikashvili commented on src/app/shared/components/slider/slider.component.ts
> +  private currentIndex = 0;
`private` სახელები იწყებოდეს `_` პრეფიქსით

2023-06-08 13:56 UTC, aberikashvili commented on src/app/shared/components/slider/slider.component.ts
> +    this.getSliderData();
ცარიელი მეთოდის გამოძახებას რა აზრი აქვს?

2023-06-08 13:57 UTC, aberikashvili commented on src/app/shared/components/slider/slider.component.ts
> +    this.slide(this.currentIndex);
```suggestion
    }
    
    this.slide(this.currentIndex);
```

2023-06-08 13:57 UTC, aberikashvili commented on src/app/shared/components/slider/slider.component.ts
> +    this.slide(this.currentIndex);
```suggestion
    }
    
    this.slide(this.currentIndex);
```

2023-06-08 13:59 UTC, aberikashvili requested changes
კომენტარები და rebase

2023-06-08 17:58 UTC, NikaBeruashvilii commented
მზადაა

2023-06-09 11:29 UTC, aberikashvili approved these changes

2023-06-09 11:29 UTC, merged