feature/project-details-სტრუქტურის-გასწორება
aberikashvili/cc-angular pull request #28
Opened 2023-06-06 12:38 UTC by NikaBeruashvilii

2023-06-12 10:05 UTC, aberikashvili requested changes
ეს ფილტრი არ მუშაობს მგონი, და "დასრულებული" ღილაკს რომ ვაჭერ გადადის დეტალებზე. არ ვიცი ეს წინა რევიუზე გაგვეპარა, ტესტირებაზე თუ სად, მაგრამ აშკარად გასაწორებელია

![image](https://github.com/aberikashvili/cc-angular/assets/3863691/e7232072-0da4-4f88-8a02-7d810652446e)

2023-06-12 10:39 UTC, NikaBeruashvilii commented
ეგრეც უნდა იყოს, project-details ის ფეიჯზე უნდა გადაავიდეს

2023-06-12 10:47 UTC, NikaBeruashvilii commented
აქამდე მასე ვიცოდით და ახლა გაარკვია თამარმა და  როგორც ჩანს ფილტრაცია უნდა იყოს და მანდ არსად არუნდა გადაიყვანოს ქლიქზე

2023-06-19 19:59 UTC, aberikashvili approved these changes

2023-06-19 19:59 UTC, merged