feature/header-link-status
aberikashvili/cc-angular pull request #30
Opened 2023-06-13 10:13 UTC by NikaBeruashvilii

2023-06-15 10:41 UTC, aberikashvili commented on src/app/shared/components/header/header.component.html
> +              href="/home"
ეს routerLink-ით გადავაკეთოთ

2023-06-15 10:42 UTC, aberikashvili commented on src/app/shared/components/header/header.component.html
> +              href="/home"
მენიუს ყველა ლინკი `routerLink` -ით იყოს

2023-06-15 10:42 UTC, aberikashvili commented on src/app/shared/components/header/header.component.scss
> +
ფორმატირება დაცულია, კარგია!

2023-06-15 10:43 UTC, aberikashvili commented on src/app/shared/components/header/header.component.ts
> +  constructor(private router: Router) {}
`private` მოდიფიკატორით შემოტანილი სერვისების სახელები უნდა იწყებოდეს `_` -ით:

```
private _router: Router
```

2023-06-15 10:44 UTC, aberikashvili requested changes
რამდენიმე კომენტარია შესასწორებელი

2023-06-19 19:57 UTC, aberikashvili commented on src/app/shared/components/header/header.component.ts
> +  constructor(private _router: Router) {}
წაშალე

2023-06-19 19:57 UTC, aberikashvili requested changes
+ 1 ახალი კომენტარი

2023-06-20 10:47 UTC, NikaBeruashvilii commented
მზადააა დასამერჯად

2023-06-20 15:18 UTC, aberikashvili approved these changes

2023-06-20 15:18 UTC, merged