Feature/our service responsive
aberikashvili/cc-angular pull request #31
Opened 2023-06-15 14:27 UTC by Gega-Rostomashvili

2023-06-19 20:05 UTC, aberikashvili commented on src/app/modules/home/components/services/services.component.scss
> +    margin-top: -8px;
ზოგადად ჯობია უარყოფითი მარჯინები არ დავწეროთ ხოლმე

2023-06-19 20:08 UTC, aberikashvili requested changes
1. კოდის ფორმატირება არეულია
2. დაკომენტარებული კოდია ისევ დატოვებული

ასეთი კომენტარი უკვე ვეღარ ვითვლი მერამდენედ დავწერე, ეს კომენტარები იმიტომ იწერება რომ მომდევნო დავალებებში იქნეს გათვალისწინებული და უკეთესი ხარისხი მივიღოთ უფრო სწრაფად. ყოველ ახალ Pull Request-ზე თუ იგივე შეცდომები განმეორდა, გამოდის ვერაფერს ვსწავლობთ

2023-06-20 10:45 UTC, Gega-Rostomashvili commented on src/app/modules/home/components/services/services.component.scss
> +    margin-top: -8px;
კი ვიცი,ვერანაირად ავწიე ოდნავ ზემოთ და იძულებულივიყავი უარყოფითი გამომეყენებინა...

2023-06-20 15:19 UTC, aberikashvili approved these changes

2023-06-20 15:19 UTC, merged