Feature/footer-mobile
aberikashvili/cc-angular pull request #35
Opened 2023-06-21 09:13 UTC by NikaBeruashvilii

2023-06-22 19:51 UTC, aberikashvili commented on src/app/shared/components/footer/footer.component.ts
> +  imageUrl = './assets/images/dropdownUp.jpg';
```suggestion
  imageUrl = '/assets/images/dropdownUp.jpg';
```

2023-06-22 19:52 UTC, aberikashvili reviewed
1 კომენტარი + rebase

2023-06-22 19:52 UTC, aberikashvili requested changes
1 კომენტარი + rebase

2023-06-23 10:46 UTC, NikaBeruashvilii commented
mzaadaa

2023-06-23 12:04 UTC, aberikashvili approved these changes

2023-06-23 12:04 UTC, merged