Feature/need our help mobile
aberikashvili/cc-angular pull request #37
Opened 2023-06-22 13:16 UTC by NikaBeruashvilii

2023-06-22 19:53 UTC, aberikashvili commented on src/app/modules/home/home.component.html
კომენტარები

2023-06-22 19:54 UTC, aberikashvili requested changes
1 კომენტარი

2023-06-23 09:40 UTC, NikaBeruashvilii commented
მზადააა

2023-06-23 12:05 UTC, aberikashvili approved these changes

2023-06-23 12:05 UTC, merged