our services
aberikashvili/cc-angular pull request #7
Opened 2023-05-03 15:40 UTC by Gega-Rostomashvili

2023-05-14 09:49 UTC, aberikashvili commented on src/app/modules/demo/demo.component.html
ამ ფაილში ცვლილებების შეტანა არ არის საჭირო, დააბრუნე

2023-05-14 09:49 UTC, aberikashvili commented on src/app/modules/home/components/our-services/our-services.component.html
> +
ცარიელი სივრცეები წაშალე

2023-05-14 09:49 UTC, aberikashvili commented on src/app/modules/home/components/our-services/our-services.component.html
> +
ცარიელი სივრცეები წაშალე

2023-05-14 09:49 UTC, aberikashvili commented on src/app/modules/home/components/our-services/our-services.component.html
> +
ცარიელი სივრცე

2023-05-14 09:51 UTC, aberikashvili commented on src/app/modules/home/components/our-services/our-services.component.html
> +            <li>{{card.description}}</li>
აქ როგორც მახსოვს ჩადგმული `*ngFor`-ი უნდა გაგეკეთებინა, არა?

2023-05-14 09:51 UTC, aberikashvili commented on src/app/modules/home/components/our-services/our-services.component.scss
> +p{
სპეციფიური კლასი აღწერე

2023-05-14 09:51 UTC, aberikashvili commented on src/app/modules/home/components/our-services/our-services.component.scss
> +
წაშალე

2023-05-14 09:54 UTC, aberikashvili commented on src/app/modules/home/components/our-services/our-services.component.ts
> +    },
```
{
      title: 'სუსტი დენები',
      services: [
        'კომპიუტერია, ტელეფონია, ტელევიზია',
        'ხანძარსაწინააღმდეგო სიგნალიზაცია,',
        'ვიდეო მეთვალყურეობა',
        'ფონური მუსიკა',
        'სისტემების კომპიუტერული მართვა (BMS)',
      ],
    }
```

2023-05-16 10:52 UTC, aberikashvili commented on src/app/modules/home/components/our-services/our-services.component.html
> +            <li>{{card.description}}</li>
ეს და-resolve-ებული კი გაქვს, მაგრა, კოდი არ შეცვლილა და დაფუშვა ხომ არ დაგავიწყდა?

2023-05-16 11:29 UTC, aberikashvili commented on src/app/modules/home/components/services/services-module.ts
მოდული აქ არ არის საჭირო

2023-05-16 11:30 UTC, aberikashvili requested changes
1 კომენტარია გასაწორებელი და კონფლიქტები დასა-fix-ი

2023-05-22 21:34 UTC, aberikashvili commented
rebase, resolve conflicts.

ნიკას კომიტები რატომ არის ამ ბრენჩში? @Gega-Rostomashvili @NikaBeruashvilii 
![image](https://github.com/aberikashvili/cc-angular/assets/3863691/cb13f3e4-cf9c-43ff-a078-d95e84a573da)

2023-05-27 19:40 UTC, aberikashvili commented on src/app/modules/home/components/services/services.component.html
> +    <!-- <img src="'/assets/img/ourservicesVector.jpg'" alt=""> -->
წაშალე

2023-05-27 19:42 UTC, aberikashvili commented on src/app/modules/home/components/services/services.component.ts
> +services: any;
ამას არსად არ იყენებ, წაშალე

2023-05-27 19:42 UTC, aberikashvili commented on src/app/modules/home/components/services/services.component.ts
> +  ngAfterViewInit(): void {}
წაშალე

2023-05-27 19:42 UTC, aberikashvili commented on src/app/modules/home/home.component.html
> +   <app-my-partners-section></app-my-partners-section>
ფორმასტირება გაასწორე

2023-05-27 19:43 UTC, aberikashvili requested changes
რამდნეიმე კომენტარია შესასწორებელი

2023-06-01 21:45 UTC, aberikashvili commented on src/app/modules/demo/demo.component.html
> + Demo Page
**Out of scope change**

ეს ცვლილება არ არის საჭირო, დააბრუნე

2023-06-01 21:45 UTC, aberikashvili commented on src/app/modules/home/components/services/services.component.html
ფორმატირება გაასწორე

2023-06-01 21:46 UTC, aberikashvili commented on src/app/modules/home/components/services/services.component.scss
ფორმატირება გაასწორე

2023-06-01 21:46 UTC, aberikashvili commented on src/app/modules/home/components/services/services.component.ts
ფორმატირება გაასწორე

2023-06-01 21:47 UTC, aberikashvili commented on src/app/modules/home/components/services/services.component.ts
> +    },
ეს არ მგონია საჭირო იყოს, სცადე თუ ამის წაშლა არაფერს აფუჭებს, მაშნ წაშალე

2023-06-01 21:47 UTC, aberikashvili requested changes
რამდნეიმე კომენტარია შესასწორებელი

2023-06-02 09:18 UTC, Gega-Rostomashvili commented on src/app/modules/home/components/services/services.component.ts
> +    },
რო წავშალე ერთი ქარდით მეტზე გადადის,ამიტომ დავტოვე..

2023-06-02 15:02 UTC, merged